<a href="https://colab.research.google.com/github/rajatlamsal00977/Project-1/blob/main/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   Rajat Lamsal
*   Bishnu Rijal
*   Pratim khadka




  Instructor: Nicolas Jachob.

  CPSMA 4413 NUMERICAL METHODS -01.





To write an algorithm (Gauss Jordan Elimination) for solving the given system of linear equation.

In [133]:
import math
import numpy as np


Gauss Jordan elimination is the algorithm to solve the system of linear equation which utilizes the 3 methods which are as:

* Swap the position of two rows.
* Multiply row by a non zero scalar
* Subtract or Add scalar multiple of one matrix to another.





Any given linear or other form of equation can be arranged into matrices as demonstrated below.

$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right.
$$


$$
\left[
\begin{array}{ccc|c}
a_{1,1} & \dots & a_{1,n} & y_1\\
\vdots&\ddots&\vdots&\vdots\\
a_{n,1} &\dots& a_{n,n}&y_n
\end{array}
\right]
$$

Lets define a matrix array

In [134]:
A = np.array([[5,4,3],[8,7,6]])

In [135]:
A

array([[5, 4, 3],
       [8, 7, 6]])

In [136]:
def Rows_add(matrix,targetRow, modifierRow, value): 
  newRow = matrix[targetRow,:]+value*matrix[modifierRow,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != targetRow:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newRow)
  return np.array(newMatrix)



In [137]:
Rows_add(A,0,1,10)

array([[85, 74, 63],
       [ 8,  7,  6]])

We are now going to write a code that will swap the Rows using dictionary.

In [138]:
def Rows_swap(matrix, row1, row2):
    dic = {row1:row2,row2:row1} 
    list = [dic.get(x,x) for x in range(len(matrix))] 
    return matrix[list]

In [139]:
Rows_swap(A,0,1)

array([[8, 7, 6],
       [5, 4, 3]])

In [140]:
def changeToLeadingOne(matrix,row,column):
  newMatrix =[]
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(1/matrix[row,column]*matrix[row,:])
  return np.array(newMatrix)


In [141]:
changeToLeadingOne(A,1,0)

array([[5.   , 4.   , 3.   ],
       [1.   , 0.875, 0.75 ]])

In [142]:
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = changeToLeadingOne(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = Rows_add(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
      newMatrix = Rows_add(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix


In [143]:
gaussJordan(A)

array([[ 1.,  0., -1.],
       [ 0.,  1.,  2.]])

Lets try another Matrix If it will work for that.

In [144]:
B = np.array([[2,4,6,8],[3,5,8,5],[9,7,6,5]])
B

array([[2, 4, 6, 8],
       [3, 5, 8, 5],
       [9, 7, 6, 5]])

In [145]:
gaussJordan(B)

array([[ 1. ,  0. ,  0. , -5.4],
       [ 0. ,  1. ,  0. , 11.6],
       [-0. , -0. ,  1. , -4.6]])

As we have seen another Matrix is also been solved by this algorithm which suggests that our code is working perfectly.

Calculating the Inverse.<br>
Here, we are going to try to compute inverse matrix by using the method where we use row operations on our matrix until we get the inverse. we first try to augment our matrix to take identity matrix out and use the remaining square matrix as computed in traditional method.


 We know the inverse is given by, $$
\left[A|I\right] \to \left[I|A^{-1}\right]
$$ 
So,lets try 
$$
A=\left[
\begin{array}{cc}
1&2\\
3&4
\end{array}
\right]
$$

In [146]:
C = np.array([[1,2,1,0],[3,4,0,1]])

In [147]:
gaussJordan(C)

array([[ 1. ,  0. , -2. ,  1. ],
       [-0. ,  1. ,  1.5, -0.5]])

So I think $A^{-1}$ is
$$
A^{-1}=\left[
\begin{array}{cc}
-2&1\\
\frac32&-\frac12
\end{array}
\right]
$$<br>
 We could cross check the  value ,
 

In [148]:
Ainverse = np.array([[-2,1],[1.5,-0.5]])
Anew = np.array([[1,2],[3,4]])

In [149]:
Anew @ Ainverse

array([[1., 0.],
       [0., 1.]])

We came to find out that the Gauss- Jordan Elimination can be applied to the given system of linear equation which involves different functions like swapping the rows, multiplying the row with some constant and adding/subtracting  that constant to the given row in order to reduce down the coefficient to zero.



Among the various limitations of Gauss-Jordan Elimination the inaccuracy due to rounding of the augmented matrix is very common. It is particularly seen while we use the coefficents in Decimal form. For example if we take an equation 
-0.8929x + 0.594y +0.4998z
and while turning it into matrix form,if we truncate first coefficent to 0.9 we can have a higher value of truncation error.