<a href="https://colab.research.google.com/github/rajatlamsal00977/Project-1/blob/main/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np


Gauss Jordan elimination is the algorithm to solve the system of linear equation which utilizes the 3 methods which are as:

* Swap the position of two rows.
* Multiply row by a non zero scalar
* Subtract or Add scalar multiple of one matrix to another.





Any given linear or other form of equation can be arranged into matrices as demonstrated below.

$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right.
$$


$$
\left[
\begin{array}{ccc|c}
a_{1,1} & \dots & a_{1,n} & y_1\\
\vdots&\ddots&\vdots&\vdots\\
a_{n,1} &\dots& a_{n,n}&y_n
\end{array}
\right]
$$

Lets define a matrix array

In [ ]:
A = np.array([[5,4,3],[8,7,6]])

In [ ]:
A

array([[5, 4, 3],
       [8, 7, 6]])

In [ ]:
def addRows(matrix,targetRow, modifierRow, value):
  newRow = matrix[targetRow,:]+value*matrix[modifierRow,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != targetRow:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newRow)
  return np.array(newMatrix)



In [ ]:
addRows(A,0,1,10)

array([[85, 74, 63],
       [ 8,  7,  6]])

We are now going to write a code that will swap the Rows using dictionary.

In [ ]:
def swapRows(matrix, row1, row2):
    dic = {row1:row2,row2:row1} 
    list = [dic.get(x,x) for x in range(len(matrix))] 
    return matrix[list]

In [ ]:
swapRows(A,0,1)

array([[8, 7, 6],
       [5, 4, 3]])

In [ ]:
def changeToLeadingOne(matrix,row,column):
  newMatrix =[]
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(1/matrix[row,column]*matrix[row,:])
  return np.array(newMatrix)


In [ ]:
changeToLeadingOne(A,1,0)

array([[5.   , 4.   , 3.   ],
       [1.   , 0.875, 0.75 ]])

In [ ]:
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = changeToLeadingOne(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = addRows(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
      newMatrix = addRows(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix


In [ ]:
gaussJordan(A)

array([[ 1.,  0., -1.],
       [ 0.,  1.,  2.]])

Lets try another Matrix If it will work for that.

In [ ]:
B = np.array([[2,4,6,8],[3,5,8,5],[9,7,6,5]])
B

array([[2, 4, 6, 8],
       [3, 5, 8, 5],
       [9, 7, 6, 5]])

In [ ]:
gaussJordan(B)

array([[ 1. ,  0. ,  0. , -5.4],
       [ 0. ,  1. ,  0. , 11.6],
       [-0. , -0. ,  1. , -4.6]])

As we have seen another Matrix is also been solved by this algorithm which suggests that our code is working perfectly.

array([[  1.,   0., -16.],
       [ -0.,   1.,   6.]])